cookie:
  expiry_days: 0
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    "\uB85C\uADF8\uC778":
      name: "\uB85C\uADF8\uC778\uD14C\uC2A4\uD2B8"
      password: $2b$12$cqv40YQDn2/l8pdoz3drmO2Kg86x5m6IkYR.CuOItItCxf6ofRuXC
    "\uC624\uAD6C":
      name: "\uC624\uAD6C\uC758\uBAA8\uD5D8"
      password: $2b$12$qOfOBcmd8Mt1rIkn5bQEcOlOTRUQhRaeZSRVrLJSPL7hpJO.x.zOa
preauthorized:
  emails:
  - melsby@gmail.com


